query GetEmployee($slug: String!) {
  employees(filters: { slug: { eq: $slug } }) {
    data {
      attributes {
        fullname
        position
        bio
        email
        googleScholarLink
        publications {
          id
          title
        }
        photo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
      }
    }
  }
}
