query GetProgram($slug: String!) {
  programs(where: { slug: $slug }) {
    name
    level
    form
    specialization
    term
    price
    program
    photos {
      id
      url
      alternativeText
    }
    cards {
      ... on ComponentCardCardBlock {
        id
        slug
        title
        subtitle
        cards {
          id
          variant
          title
          description
          icon {
            url
            alternativeText
          }
        }
      }
      ... on ComponentArticleArticle {
        id
        slug
        title
        subtitle
        content
        photos {
          id
          url
          alternativeText
        }
      }
    }
    location {
      title
      address
      phone
      email
      list {
        id
        title
      }
      latitude
      longitude
    }
  }
}
