query GetSkeleton {
  footer {
    data {
      attributes {
        additionalText
        sections {
          id
          title
          links {
            id
            title
            link
          }
        }
        location {
          data {
            attributes {
              title
              address
              phone
              email
              social {
                facebook
                instagram
                twitter
                telegram
                youtube
              }
            }
          }
        }
      }
    }
  }
}
