query GetSkeleton {
  navigations {
    id
    title
    path
    items {
      id
      title
      path
    }
  }
  footer {
    additionalText
    sections {
      title
      links {
        id
        title
        path
      }
    }
    location {
      title
      address
      phone
      email
      social {
        facebook
        instagram
        twitter
        telegram
        youtube
      }
    }
  }
}
