query GetEntrantPage {
  page(id: 7) {
    data {
      attributes {
        title
        subtitle
        programs {
          data {
            attributes {
              slug
              name
              level
              form
              specialization
              term
              program
              cards {
                ... on ComponentPageCardBlock {
                  id
                  title
                }
                ... on ComponentPageArticle {
                  id
                  title
                }
              }
            }
          }
        }
        location {
          data {
            attributes {
              title
              address
              phone
              email
              list {
                id
                title
              }
              latitude
              longitude
            }
          }
        }
      }
    }
  }
}
