query GetContactPage {
  contact {
    title
    subtitle
    location {
      phone
      email
      address
      latitude
      longitude
      social {
        facebook
        instagram
        telegram
        twitter
        youtube
      }
    }
  }
}
