query GetContactPage {
  page(id: 14) {
    data {
      attributes {
        title
        subtitle
        location {
          data {
            attributes {
              phone
              email
              address
              latitude
              longitude
              social {
                facebook
                instagram
                telegram
                twitter
                youtube
              }
            }
          }
        }
      }
    }
  }
}
