query GetIndexPage {
  index {
    title,
    subtitle,
    button {
      title,
      path,
    },
    videoLink,
    partnershipText,
    partnershipIcons {
      id, 
      url,
      alternativeText,
    }
  }
}
