query GetIndexPage {
  home {
    data {
      attributes {
        title
        subtitle
        button {
          title
          link
        }
        speciality
        specialization
        videoLink
        partnershipText
        partnershipIcons {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
        university {
          title
          link
        }
        universityLogo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
        instituteLogo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
        institute {
          title
          link
        }
      }
    }
  }
}
