query GetPage($slug: String!) {
  pages(filters: { slug: { eq: $slug } }) {
    data {
      attributes {
        title
        subtitle
        content {
          ... on ComponentPageArticle {
            id
            title
            subtitle
            content
            photos {
              data {
                attributes {
                  hash
                  url
                  alternativeText
                }
              }
            }
          }
          ... on ComponentListLink {
            id
            title
            link
          }
          ... on ComponentPageGallery {
            id
            title
            subtitle
            type
            photos {
              data {
                attributes {
                  hash
                  url
                  alternativeText
                }
              }
            }
          }
          ... on ComponentPageListBlock {
            id
            title
            subtitle
            list {
              id
              title
              link
            }
          }
          ... on ComponentPageCardBlock {
            title
            subtitle
            cards {
              id
              title
              description
              variant
              icon {
                data {
                  attributes {
                    hash
                    url
                    alternativeText
                  }
                }
              }
            }
          }
        }
        location {
          data {
            attributes {
              title
              address
              phone
              email
              latitude
              longitude
              list {
                id
                title
                link
              }
              social {
                facebook
                instagram
                twitter
                twitter
                youtube
              }
            }
          }
        }
        programs {
          data {
            attributes {
              slug
              name
              level
              form
              specialization
              term
              program
              cards {
                ... on ComponentPageCardBlock {
                  id
                  title
                }
                ... on ComponentPageArticle {
                  id
                  title
                }
              }
            }
          }
        }
      }
    }
  }
}
