query GetCompetitionPage {
  competition {
    article {
      title
      subtitle
      content
      photos {
        id
        url
        alternativeText
      }
    }
    gallery {
      title
      subtitle
      photos {
        id
        url
        alternativeText
      }
    }
  }
}
