query GetSyllabiPage {
  syllabi(sort: "year:asc") {
    data {
      attributes {
        discipline
        link
        year
        employees {
          data {
            attributes {
              slug
              fullname
            }
          }
        }
      }
    }
    
  }
  page(id: 11) {
    data {
      attributes {
        title
        subtitle
      }
    }
  }
}
