query getNewsPage($start: Int = 0, $limit: Int = 9) {
  posts(
    pagination: { start: $start, limit: $limit }
    sort: "order:desc"
  ) {
    meta {
      pagination {
        total
      }
    }
    data {
      attributes {
        title
        description
        slug
        category {
          data {
            attributes {
              name
              slug
            }
          }
        }
        photo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
      }
    }
  }
}
