query getNewsPage($start: Int = 0, $limit: Int = 9) {
  postsConnection {
    aggregate {
      count
    }
  }
  posts(start: $start, limit: $limit, sort: "published_at:desc") {
    id
    title
    description
    slug
    category {
      name
      slug
    }
    photo {
      url
    }
  }
}
