query getNewsPage {
  page(id: 13) {
    data {
      attributes {
        title
        subtitle
      }
    }
  }
  pinnedPosts: posts(
    filters: { pinned: { eq: true } }
    sort: "publishedAt:desc"
  ) {
    data {
      attributes {
        title
        description
        slug
        category {
          data {
            attributes {
              name
              slug
            }
          }
        }
        photo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
      }
    }
  }
}
