query GetNews($slug: String!, $limit: Int = 3) {
  relatedPosts: posts(
    filters: { slug: { ne: $slug } }
    pagination: { limit: $limit }
    sort: "publishedAt:desc"
  ) {
    data {
      attributes {
        title
        description
        slug
        category {
          data {
            attributes {
              name
              slug
            }
          }
        }
        photo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
      }
    }
  }

  posts(filters: { slug: { eq: $slug } }) {
    data {
      attributes {
        title
        description
        content
        slug
        category {
          data {
            attributes {
              name
              slug
            }
          }
        }
        photo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
      }
    }
  }
}
