query GetHistoryPage {
  history {
    title
    subtitle
    content
    image {
      url
      alternativeText
    }
    location {
      title
      address
      phone
      email
      list {
        id
        title
      }
      latitude
      longitude
    }
    gallery {
      title
      subtitle
      photos {
        id
        url
        alternativeText
      }
    }
  }
}
