query GetStaffPage {
  page(id: 2) {
    data {
      attributes {
        title
        subtitle
      }
    }
  }
  employees(sort: "order:desc") {
    data {
      attributes {
        slug
        fullname
        position
        photo {
          data {
            attributes {
              hash
              url
              alternativeText
            }
          }
        }
      }
    }
  }
}